name: Playit RDP Tunnel

on:
  workflow_dispatch:

jobs:
  setup-rdp-tunnel:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget openssh-server xrdp

    - name: Download and Install Playit
      run: |
        wget -O playit https://github.com/playit-cloud/playit-agent/releases/download/v0.15.26/playit-linux-x86_64
        chmod +x playit
        sudo mv playit /usr/local/bin/

    - name: Configure xRDP and SSH
      run: |
        sudo systemctl enable xrdp
        sudo systemctl start xrdp
        sudo systemctl enable ssh
        sudo systemctl start ssh

    - name: Start Playit and Set Up RDP Tunnel
      env:
        PLAYIT_AUTH_KEY: ${{ secrets.PL }}
      run: |
        nohup playit --secret $PLAYIT_AUTH_KEY &

    # Prevent workflow from stopping
    - name: Keep the GitHub Action Runner Alive
      run: |
        sleep 11800  # Adjust the duration as needed
