name: Playit RDP Tunnel

on:
  workflow_dispatch:

jobs:
  setup-rdp-tunnel:
    runs-on: windows-latest

    steps:
    # Descargar el repositorio (si es necesario)
    - name: Check out the repository
      uses: actions/checkout@v2

    # Descargar e instalar Playit
    - name: Download and Install Playit
      run: |
        # Descargar el ejecutable de Playit para Windows
        Invoke-WebRequest -Uri "https://github.com/playit-cloud/playit-agent/releases/download/v0.15.26/playit-windows-x86_64-signed.exe" -OutFile "$env:USERPROFILE\playit.exe"
        # Esperar unos segundos para asegurar que se descargue correctamente
        Start-Sleep -Seconds 5

    # Configurar Remote Desktop Protocol (RDP) en Windows
    - name: Enable Remote Desktop
      run: |
        # Habilitar conexiones RDP
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        # Habilitar reglas del firewall para RDP
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        # Configurar autenticación de usuario para RDP
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1
        # Configurar una contraseña para el usuario "runneradmin"
        Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "p@ssw0rd!" -Force)

    # Iniciar Playit y configurar el túnel RDP
    - name: Start Playit and Set Up RDP Tunnel
      env:
        PLAYIT_AUTH_KEY: ${{ secrets.PL }}  # Asegúrate de configurar este secreto en tu repositorio
      run: |
        # Iniciar Playit con la clave secreta proporcionada por los secretos del repositorio
        Start-Process -FilePath "$env:USERPROFILE\playit.exe" -ArgumentList "--secret $env:PLAYIT_AUTH_KEY" -NoNewWindow -Wait

    # Mantener vivo el runner para permitir acceso remoto durante el tiempo deseado
    - name: Keep the GitHub Action Runner Alive
      run: |
        # Mantener la acción activa durante aproximadamente 3 horas y 16 minutos (ajusta según sea necesario)
        Start-Sleep -Seconds 11800
